## 판다스 자료구조(엑셀의 형태로 나타냄)

In [2]:
import pandas as pd

### 1. Series: 1차원 데이터

In [104]:
obj = pd.Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [9]:
#series는 자동으로 인덱싱이 붇는다.
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj.values #series 데이터에서 values 속성을 얻어왔을때 ndarray임을 알수 있다.

array([ 4,  7, -5,  3], dtype=int64)

In [12]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
np.array([4,7,-5,3])

array([ 4,  7, -5,  3])

In [15]:
#인덱싱
obj[0]

4

In [16]:
obj2['d']#obj2[0] 도 가능

4

In [17]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [18]:
obj> 0

d     True
b     True
a    False
c     True
dtype: bool

In [19]:
obj2[obj>0]

d    4
b    7
c    3
dtype: int64

In [20]:
obj2 * 2 #브로드캐스팅을 가능

d     8
b    14
a   -10
c     6
dtype: int64

In [21]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [22]:
obj2 # key-value쌍(dictionary)의 형태를 띰

d    4
b    7
a   -5
c    3
dtype: int64

In [23]:
'd' in obj2

True

In [24]:
'e' in obj2

False

In [27]:
dictionary = {'Ohio':3500, 'Texas':71000, 'Orgen':16000, 'Utah':5000}
obj3 = pd.Series(dictionary)
obj3

Ohio      3500
Texas    71000
Orgen    16000
Utah      5000
dtype: int64

In [28]:
states = ['Califonia', 'Ohio','Orgen', 'Texas']
obj4 = pd.Series(dictionary, index = states )
obj4 # 원래 기존에있는 값은 유지하며, 새로운 인덱스의 'Califonia'는 새롭게 추가가됨.

Califonia        NaN
Ohio          3500.0
Orgen        16000.0
Texas        71000.0
dtype: float64

In [29]:
pd.isnull(obj4) # 널값을 찾아내는 모듈 obj4.isnull() 가능

Califonia     True
Ohio         False
Orgen        False
Texas        False
dtype: bool

In [30]:
pd.notnull(obj4)# 널이 아닌 값을 찾아내는 모듈 obj4.notnull() 가능

Califonia    False
Ohio          True
Orgen         True
Texas         True
dtype: bool

In [31]:
#series의 네임을 정할 수있음.
obj4.name = "popluation"
obj4

Califonia        NaN
Ohio          3500.0
Orgen        16000.0
Texas        71000.0
Name: popluation, dtype: float64

In [33]:
obj4.index.name  = "state" 
obj4

state
Califonia        NaN
Ohio          3500.0
Orgen        16000.0
Texas        71000.0
Name: popluation, dtype: float64

In [34]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj # 임의로 인덱스를 설정이 가능하다.

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 실습

* 딕셔너리-> 시리즈 변환 (index, values 출력)

In [36]:
dict_data = {'a': 1, 'b': 2, 'c': 3}

In [37]:
obj1 = pd.Series(dict_data)
obj1

a    1
b    2
c    3
dtype: int64

In [38]:
obj1.index

Index(['a', 'b', 'c'], dtype='object')

In [39]:
obj1.values

array([1, 2, 3], dtype=int64)

* 리스트 -> 시리즈 변환 (index, values 출력)

In [41]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

In [42]:
obj2 = pd.Series(list_data)
obj2

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [43]:
obj2.index

RangeIndex(start=0, stop=5, step=1)

In [44]:
obj2.values

array(['2019-01-02', 3.14, 'ABC', 100, True], dtype=object)

* 튜플 -> 시리즈 변환 (index, values 출력)

In [45]:
tup_data = ('영인', '2010-05-01', '여', True)

In [46]:
obj3 = pd.Series(list_data)
obj3

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [47]:
obj3.index

RangeIndex(start=0, stop=5, step=1)

In [48]:
obj3.values

array(['2019-01-02', 3.14, 'ABC', 100, True], dtype=object)

* 튜플 -> 시리즈 변환 (index 설정)

In [50]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name=['이름', '생년월일', '성별', '학생여부']

In [52]:
obj4 = pd.Series(tup_data, index = index_name)
obj4

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

* 시리즈 원소 선택

In [53]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name=['이름', '생년월일', '성별', '학생여부']

In [54]:
obj5 = pd.Series(tup_data, index = index_name)
obj5

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [ ]:
# 색인을 통해 '영인' 값 얻어오기

In [57]:
obj5['이름']

'영인'

In [ ]:
# 색인(슬라이싱)을 통해 ''2010-05-01'과 '여' 선택하기

In [59]:
obj5[['생년월일', '성별']]

생년월일    2010-05-01
성별               여
dtype: object

In [60]:
obj5[[1,2]]

생년월일    2010-05-01
성별               여
dtype: object

In [61]:
obj5['생년월일':'성별']

생년월일    2010-05-01
성별               여
dtype: object

In [63]:
obj5[1:3]

생년월일    2010-05-01
성별               여
dtype: object

### 2. DataFrame :2차원 데이터

In [65]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [66]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [67]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [68]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [69]:
frame.head() #앞에 있는 5개의 데이터만 가져온다.

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [70]:
pd.DataFrame(data, columns=['year','state', 'pop']) #columns이름을 지정하고 순서도 바꿀수 있음.

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [71]:
pd.DataFrame(data, columns=['year','state', 'pop','debt'])

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [73]:
frame2 = pd.DataFrame(data, columns=['year','state', 'pop','debt'],
            index = ['one','two','three','four','five','six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [74]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [75]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [77]:
frame2['state']['four'] # 값으로만 색인

'Nevada'

In [79]:
frame2['state'] #열 색인 frame.state로도 색인이 가능하다. 간단한 단어로 구성이 되있어야한다.

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [78]:
frame2.loc['one'] #행으로 색인

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [80]:
#frame2의 2개의 행을 가져오는 방식
#슬라이싱으롤 행을 가져올때는 loc를 안써도 추출이됨.
frame2['one':'two']

year state  pop debt
one  2000  Ohio  1.5  NaN
two  2001  Ohio  1.7  NaN

In [81]:
frame2.loc['one':'two']

year state  pop debt
one  2000  Ohio  1.5  NaN
two  2001  Ohio  1.7  NaN

In [82]:
#열에 값넣기
frame2["debt"] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [83]:
frame2["debt"] = np.arange(6)
frame2 # 짝만맞으면 잘 들어간다.

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [85]:
frame2["debt"] = pd.Series([1,2,3,4,5,6], index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2 # 어디에 맵핑이 되어야 하는지  index에 지정을 해줘야한다.

year   state  pop  debt
one    2000    Ohio  1.5     1
two    2001    Ohio  1.7     2
three  2002    Ohio  3.6     3
four   2001  Nevada  2.4     4
five   2002  Nevada  2.9     5
six    2003  Nevada  3.2     6

In [86]:
frame2["debt"] = pd.Series([1,3,5], index=['one', 'three', 'five'])
frame2 # 어디에 맵핑이 되어야 하는지  index에 지정을 해줘야한다. 부분부분도 값넣기가 가능

year   state  pop  debt
one    2000    Ohio  1.5   1.0
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   3.0
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   5.0
six    2003  Nevada  3.2   NaN

In [88]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3 #key값이 컬럼으로 내부에있는 key값은 행의 인덱스로 들어간다.

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [89]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [90]:
frame3 = pd.DataFrame(pop, index=[2001,2002,2003])
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [91]:
frame3.name = "population"
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [92]:
frame3.index.name="year"
frame3.columns.name="state"
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2003      NaN   NaN

### 3. Index
- 행과 열을 알려주는 메타 데이터

In [105]:
import numpy as np
a = np.array([1,2,3])
print(a[0], a[2])

1 3


In [94]:
obj = pd.Series(range(3), index=['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [96]:
obj.index[:2]

Index(['a', 'b'], dtype='object')

In [97]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [98]:
obj.index[1] = 'd' #값을 변환 못함

TypeError: Index does not support mutable operations

In [99]:
labels = pd.Index(np.arange(3))

pd.Series([1, 2, 3], index=labels)

0    1
1    2
2    3
dtype: int64

### 실습

* 딕셔너리->데이터프레임 변환

In [100]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

In [115]:
df1 = pd.DataFrame(dict_data)
df1

c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

* 행인덱스/ 열 이름 설정

In [107]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [110]:
# 준서, 예은 -> '학생1', '학생2'

df.index=["학생1", "학생2"]
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [111]:
# 나이, 성별, 학교 -> '연령', '남녀', '소속'

df.columns=['연령', '남녀', '소속']
df

연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [112]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

In [ ]:
# 행인덱스/ 열 이름 변경
# rename 사용하여 변경

df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'},
         index={'준서':'학생1', '예은':'학생2'}, inplace=True)
df

## 중요한 기능들

### 1. 재색인 

In [116]:
sr = pd.Series([1,2,3,4], index=['d','b','a','c'])
sr


d    1
b    2
a    3
c    4
dtype: int64

In [120]:
sr = sr.reindex(['a','b','c','d'])
sr

a    3
b    2
c    4
d    1
dtype: int64

In [126]:
sr = pd.Series([1,2,3,4], index=[0,3,4,5])
sr

0    1
3    2
4    3
5    4
dtype: int64

In [132]:
sr.reindex(np.arange(6), method='ffill')

0    1
1    1
2    1
3    2
4    3
5    4
dtype: int64

In [130]:
sr.reindex(np.arange(6), method='bfill')

0    1
1    2
2    2
3    2
4    3
5    4
dtype: int64

### 2. 로우나 컬럼 삭제하기

In [136]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [137]:
obj.drop('c', inplace=True)
obj

a    0
b    1
d    3
e    4
dtype: int32

In [139]:
obj.drop(['a', 'd'], inplace=True)

In [140]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [142]:
#colorado 행 삭제
#axios = 0(행축), axis=1 (열축)
# drop 연산을 할경우 : 지정된 축을 삭제
#2가지 방식
data.drop('Colorado', axis=0) # 행축을 삭제
data.drop('Colorado', axis="index") # 행축을 삭제

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
#열을 삭제
data.drop("two", axis=1)
data.drop("two", axis="columns")

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [144]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### 3. 색인하기, 선택하기, 거르기

In [145]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [147]:
data[["two","one"]]

two  one
Ohio        1    0
Colorado    5    4
Utah        9    8
New York   13   12

In [151]:
#조건에 맞는 것들을 값을 바꿔주기
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* loc, iloc 선택하기

In [152]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [153]:
data.loc["Colorado"]["one"]

0

In [154]:
data.loc["Colorado"][["two","three"]]#특정 행을 가져와서 특정값범위를 지정해서 색인

two      5
three    6
Name: Colorado, dtype: int32

In [155]:
data.loc["Colorado",["two","three"]]# 다른 표현방법

two      5
three    6
Name: Colorado, dtype: int32

In [157]:
data.iloc[1] # 행을 번호로 매겨서 행 색인 모듈인 iloc

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [158]:
data.iloc[1][[1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [159]:
data.iloc[1,[1,2]]

two      5
three    6
Name: Colorado, dtype: int32

In [169]:
data.loc[:"Utah"]

AttributeError: 'dict' object has no attribute 'loc'

In [170]:
data.iloc[:3]

AttributeError: 'dict' object has no attribute 'iloc'

### 실습

* 행삭제

In [263]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준' 행 삭제

In [ ]:
# '서준', '우현' 행 삭제

* 열삭제

In [266]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '수학' 열 삭제

In [268]:
# '수학', '영어' 열 삭제

*  행선택

In [270]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준' 행 선택 (라벨 색인, 정수 색인)

In [ ]:
# '서준', '우현' 행 선택(라벨 색인, 정수 색인, 슬라이싱)

* 열선택

In [278]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '수학' 열 선택

In [ ]:
# '음악', '체육' 열 선택

* 원소 선택

In [284]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준'의 '음악' 점수

In [ ]:
#'서준'의 '음악','체육' 점수

In [ ]:
#'서준','우현'의 '음악','체육' 점수

* 열추가

In [317]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '국어' 열 추가, 값은 80 점 지정

* 행추가

In [319]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# "본인 이름" 으로 행추가, 과목 점수도 지정

* 원소값 변경

In [321]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [293]:
# '서준'의 '체육' 점수를 80 점으로 변경(라벨 색인, 정수 색인)

In [ ]:
# '서준'의 '음악','체육' 점수 변경

* 행, 열 바꾸기

In [3]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# 과목이 행, 학생이 열

In [4]:
df.T

서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [6]:
df.transpose()

서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

* 특정 열을 행 인덱스로 설정

In [8]:
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
df

이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [190]:
# '이름' 열을 행 인덱스로 시정 

In [191]:
df.set_index('이름', inplace=True)
df

수학  영어   음악   체육
이름                  
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [338]:
# reindex

In [203]:
df = df.reindex(['우현', '서준', '인아', '준혁'])
df

수학    영어     음악     체육
이름                          
우현  80.0  89.0   95.0   90.0
서준  90.0  98.0   85.0  100.0
인아  70.0  95.0  100.0   90.0
준혁   NaN   NaN    NaN    NaN

In [208]:
# reset_index 데이터프레임에 인덱스를 초기화하는 건데 실제로는 인덱스를 제거할때 많이 쓴다.

df.reset_index(drop=True, inplace=True)
df

수학    영어     음악     체육
0  80.0  89.0   95.0   90.0
1  90.0  98.0   85.0  100.0
2  70.0  95.0  100.0   90.0
3   NaN   NaN    NaN    NaN

![image](https://user-images.githubusercontent.com/85923524/176627272-3fb4205a-2822-4352-8db8-403f79b12b04.png)

In [160]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [161]:
#1
frame2["state"]

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [162]:
#2
frame2[["state","pop","debt"]]

state  pop debt
one      Ohio  1.5  NaN
two      Ohio  1.7  NaN
three    Ohio  3.6  NaN
four   Nevada  2.4  NaN
five   Nevada  2.9  NaN

In [165]:
#3
frame2.loc["two"]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: two, dtype: object

In [166]:
#4
frame2.loc["two":"four"]

year   state  pop debt
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN

In [173]:
#5
frame2.iloc[2:4, 2:4]

pop debt
three  3.6  NaN
four   2.4  NaN

In [175]:
#6 컬럼을 2개이상을 가져올 때는 중괄호는 2개로 사용해야함
frame2[["pop","debt","state"]]

pop debt   state
one    1.5  NaN    Ohio
two    1.7  NaN    Ohio
three  3.6  NaN    Ohio
four   2.4  NaN  Nevada
five   2.9  NaN  Nevada

In [178]:
#7
frame2.loc[["three","four","two"]]

year   state  pop debt
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
two    2001    Ohio  1.7  NaN